### ISSUE TITLE
Firefox: Can't change hotkey back to Alt+H

### ISSUE THREAD

**Issue by JakobBruenker** [visortelle/hackage-ui#15]
**Describe the bug**
I changed the hotkey to Alt+T, but wanted to change it back after seeing that Alt+T instead still opens the firefox tools menu when I press it. However, when trying to change it back, the Haskell spotlight popup closes, and the combination is still Alt+T.

**To Reproduce**
1. Install browser extension in firefox
2. Set hotkey to Alt+T
3. Try setting hotkey to Alt+H
4. Popup closes, hotkey remains unchanged

**Expected behavior**
The popup shouldn't close and the hotkey should change. Alternatively, have some other way I can reset the hotkey.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 96.0.3 (64 bit)

**Additional context**
I'm using xmonad but I doubt it makes a difference

**Comment by visortelle** [comment]
Thank you for the bug report. 🙂

I published a new 0.0.8 version with the fix.

https://addons.mozilla.org/en-US/firefox/addon/haskell-spotlight/versions/

https://user-images.githubusercontent.com/9302460/153058679-156de7a7-26e9-4efc-843f-33577a1ae5ec.mov

Please check and if it works for you, close this issue.

**Comment by JakobBruenker** [comment]
That was quick, thanks!

It does work, and I think the reset button is a good addition, though I have to admit that when I said "I'm using xmonad but I doubt it makes a difference" I was wrong - xmonad was in fact why I couldn't change it back.
