### ISSUE TITLE
VS Code "Error loading webview: Error: Could not register service workers: InvalidStateError:"

### ISSUE THREAD

**Issue by salimp2009** [visortelle/hackage-ui#16]
**Describe the bug**
When i activate spotlight by Alt H , i get an error 
`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

**To Reproduce**
1. Open a Haskell project
2. Click on Alt H
3. At the bottom corner of VS Code i get the error 
**`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`**

**Expected behavior**
Open a search page

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Desktop
 - OS: Windows 11
 - Browser [Chrome and also Microsoft Edge]
 - VS Code Version [1.66.2]

**Additional context**
See attached screen shot
![VSCode_HaskellSpotLight](https://user-images.githubusercontent.com/46407603/164301605-bc14d312-2183-4efa-b47e-d38b96c930e3.jpg)

**Comment by visortelle** [comment]
Hi @salimp2009

Please try to close all VSCode instances and open the extension in a new one.

If it won't help you, please try all listed solutions listed here:

https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

**Comment by salimp2009** [comment]
> Hi @salimp2009
> 
> Please try to close all VSCode instances and open the extension in a new one.
> 
> If it won't help you, please try all listed solutions listed here:
> 
> https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

thank you. After opening this issue I disable the extension at VS Code. When you sent the answer , i reenabled and now it works. It worked; i did not have to do anything else. But it seems like a general VS Code issue... Rebooting whole windows might have worked . Thanks a lot that is a great tool 

I will close it

**Comment by visortelle** [comment]
Perfect.
You are welcome. 🙂
