### ISSUE TITLE
Getting "An error occured when searching on hoogle"

### ISSUE THREAD

**Issue by KristianBalaj** [visortelle/hackage-ui#21]
**Describe the bug**

When I type anything to the searchbox I get the following error and no results are returned.

<img width="1920" alt="Screenshot 2024-05-08 at 11 05 03" src="https://github.com/haskell-spotlight/haskell-spotlight/assets/20045353/b5337712-ee63-4ecb-b8e6-1ef61459dc6a">

**Comment by fendor** [comment]
Can reproduce the issue.

Requests to the URL `https://haskell-spotlight.vercel.app/api/hoogle?mode=json&format=text&hoogle=filter&start=1&count=1000`  return a `402`. 
![image](https://github.com/haskell-spotlight/haskell-spotlight/assets/8463814/a2fada8d-5010-4b30-a1f0-89fef5225877)

**Comment by visortelle** [comment]
I will take a look in an hour.

**Comment by visortelle** [comment]
Moved the project to a free Vercel plan. Please check if it works now.

**Comment by fendor** [comment]
Works for me now!
