### ISSUE TITLE
Perhaps hide reexports in function search results?

### ISSUE THREAD

**Issue by bgamari** [visortelle/hackage-ui#3]
First, this looks quite compelling! Great work thusfar.

However, when playing around with the search function I found that it was fairly easy to stumble into searches whose results are extremely long due to reexports. For instance, see https://hackage-ui.vercel.app/?search=%3At+lookup. I suspect that these aren't particularly important for most users. Perhaps it would be a good idea to ellipsize them.

**Comment by visortelle** [comment]
Implemented here: https://github.com/visortelle/hackage-ui/commit/4db253fe27a679aa232dbb7f4d661a61aaa9fdfd

https://user-images.githubusercontent.com/9302460/148424637-dcce8989-57c2-4740-bed7-40ffe85b19b6.mov

@bgamari Please try and provide some feedback: https://hackage-ui.vercel.app/

**Comment by bgamari** [comment]
Yes, this looks much better. Thank you!
